name: Canary Publish

on:
  push:
    branches:
      - canary

jobs:
  publish:
    name: Canary build publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node files
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Clean install (CI) dependencies if lockfile (above) changed
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set git config with NPM token
        run: git config --global user.email "jack.howard@washpost.com" && git config --global user.name "jackhowa"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PERSONAL_AUTH_TOKEN }}

      - name: Get current datetime for re-running publish if necessary
        id: get-datetime
        run: echo "::set-output name=date::$(date +'%Y%m%d%H%M%S')"

      - name: Prerelease with tag, eg (`0.0.2-canary.{hash of commit}.{current-date-time}`)
        run: npm version prerelease --preid=canary.$(git rev-parse --short HEAD).${{ steps.get-datetime.outputs.date }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # publishing above version and tagging that version to this tag
      - name: Publish with the tag canary specified 
        run: npm publish --tag canary
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tag of canary
        run: git push origin canary -f
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
