name: Pull Request Test and Lint

on:
  pull_request:
    # synchronize	commit(s) pushed to the pull request
    types: [synchronize, opened]

jobs:
  ensure_minimum_test_coverage_and_lint_all_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          #  0 indicates all history for all branches and tags
          fetch-depth: 0

      - name: Setup Node with 12
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Clean install (CI) dependencies if lockfile (above) changed
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

      - name: Run tests on changed since base branch with coverage
        run: npm run test -- --changedSince=${{ github.event.pull_request.base.ref }}

      # - name: Check linting on all files
      #   run: npm run lint
