name: Stable Publish

on:
  push:
    branches:
      - stable

jobs:
  publish:
    name: Stable build publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12"
          registry-url: "https://npm.pkg.github.com"

      - name: Cache Node files
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Clean install (CI) dependencies if lockfile (above) changed
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # GITHUB_ACTOR is the username of the user that initiated the workflow run
      # https://docs.github.com/en/actions/learn-github-actions/environment-variables#default-environment-variables
      # need this config for running `npm version {version level}` commit
      - name: Iterate version patch for stable release
        run: |
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git config --local user.name "$GITHUB_ACTOR"
          npm version patch
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # publishing above version and tagging that version to this tag
      - name: Publish with the tag stable specified
        run: npm publish --tag stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push tag of stable
        run: git push origin stable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
